---
abstract: 'Debug memory leaks in Catalyst applications'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Tomas Doran <bobtfish@bobtfish.net>'
generated_by: 'Dist::Zilla version 1.093250'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-LeakChecker
requires:
  B::Deparse: 0
  Catalyst: 5.8
  Devel::Cycle: 1.11
  FindBin: 0
  Moose: 0
  MooseX::AttributeHelpers: 0
  MooseX::Types: 0
  PadWalker: 1.8
  Task::Weaken: 0
  Test::More: 0.88
  Text::SimpleTable: 0
  namespace::autoclean: 0
  namespace::clean: 0.05
version: 0.05
